name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      ##- name: Run tests
      ##  run: npm test

      - name: Deploy to Vercel
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            npx vercel --prod;
          else
            npx vercel --pre;
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
